use FoodDash;

-- 1. Create Customers Table
CREATE TABLE Customers (
    customer_id INT IDENTITY(1,1) PRIMARY KEY,
    full_name NVARCHAR(255) NOT NULL,
    city NVARCHAR(100),
    gender NVARCHAR(20),
    signup_date DATE
);

-- 2. Create Restaurants Table
CREATE TABLE Restaurants (
    restaurant_id INT IDENTITY(1,1) PRIMARY KEY,
    restaurant_name NVARCHAR(255) NOT NULL,
    city NVARCHAR(100),
    category NVARCHAR(100)
);

-- 3. Create DeliveryPartners Table
CREATE TABLE DeliveryPartners (
    partner_id INT IDENTITY(1,1) PRIMARY KEY,
    partner_name NVARCHAR(255) NOT NULL,
    city NVARCHAR(100)
);

-- 4. Create Orders Table
CREATE TABLE Orders (
    order_id INT IDENTITY(1,1) PRIMARY KEY,
    customer_id INT,
    restaurant_id INT,
    partner_id INT,
    city NVARCHAR(100),
    order_date DATETIME,
    total_amount DECIMAL(10, 2),
    delivery_fee DECIMAL(10, 2),
    status NVARCHAR(50),
    
    -- Foreign Key Constraints
    CONSTRAINT FK_Orders_Customers FOREIGN KEY (customer_id) 
        REFERENCES Customers(customer_id),
    CONSTRAINT FK_Orders_Restaurants FOREIGN KEY (restaurant_id) 
        REFERENCES Restaurants(restaurant_id),
    CONSTRAINT FK_Orders_Partners FOREIGN KEY (partner_id) 
        REFERENCES DeliveryPartners(partner_id)
);

-- 1. Display all information from the Customers table.
SELECT * 
FROM Customers;

-- 2. Display only the customer names.
SELECT full_name 
FROM Customers;

-- 3. Display the restaurant name and category.
SELECT restaurant_name, category 
FROM Restaurants;

-- 4. Display all unique cities where customers live.
SELECT DISTINCT city 
FROM Customers;

-- 5. Display the first 10 orders.
SELECT TOP 10 * 
FROM Orders 
ORDER BY order_id ASC;

-- 6. Find all delivered orders.
SELECT * 
FROM Orders 
WHERE status = 'Delivered';

-- 7. Find all cancelled orders.
SELECT * 
FROM Orders 
WHERE status = 'Cancelled';

-- 8. Show all orders whose total amount is greater than $500.
SELECT * 
FROM Orders 
WHERE total_amount > 500;

-- 9. Show all orders with a total amount between $300 and $800.
SELECT * 
FROM Orders 
WHERE total_amount BETWEEN 300 AND 800;

-- 10. Display all customers who live in Cairo.
SELECT * 
FROM Customers 
WHERE city = 'Cairo';

-- 11. Display all restaurants located in Alexandria.
SELECT * 
FROM Restaurants 
WHERE city = 'Alexandria';

-- 12. Display customers who live in either Cairo or Giza.
SELECT * 
FROM Customers 
WHERE city IN ('Cairo', 'Giza');

-- 13. Find customers whose names start with the letter A.
SELECT * 
FROM Customers 
WHERE full_name LIKE 'A%';

-- 14. Find restaurants whose names end with House.
SELECT * 
FROM Restaurants 
WHERE restaurant_name LIKE '%House';

-- 15. Display all orders placed after January 1, 2026.
SELECT * 
FROM Orders 
WHERE order_date > '2026-01-01';

-- 16. Display all orders sorted from the highest total amount to the lowest.
SELECT * 
FROM Orders 
ORDER BY total_amount DESC;

-- 17. Display all orders sorted by the lowest delivery fee.
SELECT * 
FROM Orders 
ORDER BY delivery_fee ASC;

-- 18. Display all orders sorted from the newest to the oldest.
SELECT * 
FROM Orders 
ORDER BY order_date DESC;

-- 19. How many customers are registered in the system?
SELECT COUNT(customer_id) AS TotalCustomers 
FROM Customers;

-- 20. How many restaurants are available?
SELECT COUNT(restaurant_id) AS TotalRestaurants 
FROM Restaurants;

-- 21. How many orders have been successfully delivered?
SELECT COUNT(order_id) AS DeliveredOrders 
FROM Orders 
WHERE status = 'Delivered';

-- 22. Calculate the total revenue generated from all orders.
SELECT SUM(total_amount) AS TotalRevenue 
FROM Orders;

-- 23. Calculate the total amount collected as delivery fees.
SELECT SUM(delivery_fee) AS TotalDeliveryFees 
FROM Orders;

-- 24. Calculate the average order value.
SELECT AVG(total_amount) AS AverageOrderValue 
FROM Orders;

-- 25. Calculate the average delivery fee.
SELECT AVG(delivery_fee) AS AverageDeliveryFee 
FROM Orders;

-- 26. Find the smallest order amount.
SELECT MIN(total_amount) AS SmallestOrderAmount 
FROM Orders;

-- 27. Find the highest order amount.
SELECT MAX(total_amount) AS HighestOrderAmount 
FROM Orders;

-- 28. Count the number of orders for each city.
SELECT city, COUNT(order_id) AS TotalOrders
FROM Orders
GROUP BY city;

-- 29. Calculate the total revenue generated in each city.
SELECT city, SUM(total_amount) AS TotalRevenue
FROM Orders
GROUP BY city;

-- 30. Count the number of orders for each order status.
SELECT status, COUNT(order_id) AS TotalOrders
FROM Orders
GROUP BY status;

-- 31. Calculate the total revenue generated by each restaurant.
SELECT restaurant_id, SUM(total_amount) AS TotalRevenue
FROM Orders
GROUP BY restaurant_id;

-- 32. Calculate the average order value for each city.
SELECT city, AVG(total_amount) AS AverageOrderValue
FROM Orders
GROUP BY city;

-- 33. Count how many orders were completed by each delivery partner.
SELECT partner_id, COUNT(order_id) AS CompletedOrders
FROM Orders
WHERE status = 'Delivered'
GROUP BY partner_id;

-- 34. Display cities that have processed more than 100 orders.
SELECT city, COUNT(order_id) AS TotalOrders
FROM Orders
GROUP BY city
HAVING COUNT(order_id) > 100;

-- 35. Display restaurants whose total revenue exceeds $50,000.
SELECT restaurant_id, SUM(total_amount) AS TotalRevenue
FROM Orders
GROUP BY restaurant_id
HAVING SUM(total_amount) > 50000;

-- 36. Display cities whose average order value is greater than $400.
SELECT city, AVG(total_amount) AS AverageOrderValue
FROM Orders
GROUP BY city
HAVING AVG(total_amount) > 400;

-- 37. Display delivery partners who have completed more than 80 delivered orders.
SELECT partner_id, COUNT(order_id) AS CompletedOrders
FROM Orders
WHERE status = 'Delivered'
GROUP BY partner_id
HAVING COUNT(order_id) > 80;

-- 38. How many total orders have been placed?
SELECT COUNT(order_id) AS TotalOrders
FROM Orders;

-- 39. What is the company's total revenue?
SELECT SUM(total_amount) AS TotalRevenue
FROM Orders;

-- 40. What is the average order value?
SELECT AVG(total_amount) AS AverageOrderValue
FROM Orders;

-- 41. Which city generated the highest revenue?
SELECT TOP 1 city, SUM(total_amount) AS TotalRevenue
FROM Orders
GROUP BY city
ORDER BY TotalRevenue DESC;

-- 42. Which restaurant generated the highest revenue?
SELECT TOP 1 r.restaurant_name, SUM(o.total_amount) AS TotalRevenue
FROM Orders o
JOIN Restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_name
ORDER BY TotalRevenue DESC;

-- 43. Which delivery partner completed the most deliveries?
SELECT TOP 1 dp.partner_name, COUNT(o.order_id) AS TotalDeliveries
FROM Orders o
JOIN DeliveryPartners dp ON o.partner_id = dp.partner_id
WHERE o.status = 'Delivered'
GROUP BY dp.partner_name
ORDER BY TotalDeliveries DESC;

-- 44. Which order status appears most frequently?
SELECT TOP 1 status, COUNT(order_id) AS StatusCount
FROM Orders
GROUP BY status
ORDER BY StatusCount DESC;

-- 45. List the Top 5 cities by number of orders.
SELECT TOP 5 city, COUNT(order_id) AS TotalOrders
FROM Orders
GROUP BY city
ORDER BY TotalOrders DESC;

-- 46. List all restaurants that generated more than $50,000 in revenue.
SELECT r.restaurant_name, SUM(o.total_amount) AS TotalRevenue
FROM Orders o
JOIN Restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_name
HAVING SUM(o.total_amount) > 50000;

-- 47. Find all cities where the average order value is greater than $400.
SELECT city, AVG(total_amount) AS AverageOrderValue
FROM Orders
GROUP BY city
HAVING AVG(total_amount) > 400;

-- 48. Find the top 3 restaurants by total revenue.
SELECT TOP 3 r.restaurant_name, SUM(o.total_amount) AS TotalRevenue
FROM Orders o
JOIN Restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_name
ORDER BY TotalRevenue DESC;

-- 49. Find the city with the highest average order value.
SELECT TOP 1 city, AVG(total_amount) AS AverageOrderValue
FROM Orders
GROUP BY city
ORDER BY AverageOrderValue DESC;

-- 50. List the five largest orders in the system.
SELECT TOP 5 *
FROM Orders
ORDER BY total_amount DESC;

-- 51. Count how many restaurants belong to each category.
SELECT category, COUNT(restaurant_id) AS TotalRestaurants
FROM Restaurants
GROUP BY category;

-- 52. Which restaurant category generated the most revenue?
SELECT TOP 1 r.category, SUM(o.total_amount) AS TotalRevenue
FROM Orders o
JOIN Restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.category
ORDER BY TotalRevenue DESC;

-- 53. Which month had the highest number of orders?
SELECT TOP 1 
    YEAR(order_date) AS OrderYear, 
    MONTH(order_date) AS OrderMonth, 
    COUNT(order_id) AS TotalOrders
FROM Orders
GROUP BY YEAR(order_date), MONTH(order_date)
ORDER BY TotalOrders DESC;

-- 54. Calculate the average delivery fee for each city.
SELECT city, AVG(delivery_fee) AS AverageDeliveryFee
FROM Orders
GROUP BY city;

-- 55. Find cities with more than 200 customers.
SELECT city, COUNT(customer_id) AS TotalCustomers
FROM Customers
GROUP BY city
HAVING COUNT(customer_id) > 200;

-- 56. Find restaurants that received more than 500 orders.
SELECT r.restaurant_name, COUNT(o.order_id) AS TotalOrders
FROM Orders o
JOIN Restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_name
HAVING COUNT(o.order_id) > 500;

-- 57. Build a management report showing, for each city: Number of orders, Total revenue, Average order value, Highest order value, Lowest order value.
SELECT 
    city, 
    COUNT(order_id) AS NumberOfOrders, 
    SUM(total_amount) AS TotalRevenue, 
    AVG(total_amount) AS AverageOrderValue, 
    MAX(total_amount) AS HighestOrderValue, 
    MIN(total_amount) AS LowestOrderValue
FROM Orders
GROUP BY city;